export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
export const SIGNUP_FORM = "SIGNUP_FORM";
export const AGREEMENT_REGISTER = "AGREEMENT_REGISTER";
export const VALIDATE_ERRORS_REGISTER = "VALIDATE_ERRORS_REGISTER";
export const LOGIN_FORM = "LOGIN_FORM";
export const VALIDATE_ERRORS_LOGIN = "VALIDATE_ERRORS_LOGIN";
export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
