export const LOAD_BIKES = "LOAD_BIKES";
export const ADD_BIKE = "ADD_BIKE";
export const REMOVE_BIKE = "REMOVE_BIKE";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const FILTER_PRODUCTS_BY_VARIOUS = "FILTER_PRODUCTS_BY_VARIOUS";
export const FILTER_PRODUCTS_BY_SEARCH = " FILTER_PRODUCTS_BY_SEARCH";
export const SHOW_CHECKOUT = "SHOW_CHECKOUT";
export const MODAL = "MODAL";
export const BASKET_FORM = "BASKET_FORM";
export const SELECT_SIZE = "SELECT_SIZE";
export const SELECT_COLOR = "SELECT_COLOR";
export const ADD_CHECKOUT = "ADD_CHECKOUT";
export const CLEAN_BASKET = "CLEAN_BASKET";
export const FLY_UP_MY_SITE = "FLY_UP_MY_SITE";


